### ISSUE TITLE
Extension-enabled mobile browsers note for Android users

### ISSUE THREAD

**Issue by Orangestar12** [stefanbohacek/detect-missing-adblocker#13]
Android users can use mobile browsers that support extensions such as [Kiwi Browser](https://kiwibrowser.com/) to install uBlock Origin and similar adblockers. I noticed in the source that the blocker differentiates between desktop and mobile users. Should this kind of option be mentioned?

**Comment by iam-py-test** [comment]
FYI, Kiwi browser is not supported by uBlock Origin.
I would also avoid Kiwi browser, as it disables uBlock Origin and other content blockers on a long list of websites (including some ad sites): https://github.com/kiwibrowser/src/blob/master/extensions/renderer/extension_injection_host.cc#L56

**Comment by Orangestar12** [comment]
Whether it is supported by the extension or not has no bearing on the fact that the extension *does* work as advertised with it. While your list is concerning from a privacy and trust standpoint none of the items in that list are particularly worrisome, especially for a user who already practices safe browsing.

My comment stands.

**Comment by stefanbohacek** [comment]
Hi @Orangestar12, thank you for raising the question!

The latest version of the plugin no longer uses a hard-coded list of suggestion plugins and browser extensions, and the message is fully customizable.

By default, the message contains a link to my blog where I list some popular options, and also includes a note on browser extensions that have been sold and may no longer work as expected.

**Comment by Orangestar12** [comment]
Works for me. Closing as solved, then. Thanks!

**Comment by stefanbohacek** [comment]
No problem, and thank you!
