### ISSUE TITLE
"Close" button does not work

### ISSUE THREAD

**Issue by langfingaz** [stefanbohacek/detect-missing-adblocker#15]
Hi, many thanks for this great plugin.

I have installed in on my website and visited the website with **Gnome Web**, where I have no adblock plugins installed. The informative pop-up appeared as expected, but it can't be closed by pressing the "Close" button:

![image](https://github.com/stefanbohacek/detect-missing-adblocker/assets/10504672/64c451ab-ebac-4a9a-99b4-d0a7ad3d7093)

When I repeated this test in **Firefox** with uBlock Origin disabled, I could also not close the informative pop-up.

**Comment by seefood** [comment]
+1

**Comment by stefanbohacek** [comment]
@langfingaz Thank you for reporting the issue! Unfortunately I don't have an access to this browser, would you be able to assist a bit with the debugging? Is this happening in other Linux browsers? Would you be able to share a link to your website while the plugin is enabled?

**Comment by stefanbohacek** [comment]
@langfingaz I think this should be resolved now. Can you please update the plugin to v1.1.4 and try again?

**Comment by langfingaz** [comment]
> @langfingaz I think this should be resolved now. Can you please update the plugin to v1.1.4 and try again?

Many thanks for fixing this so quickly (I didn't even manage to send you my website in time ^^). Now it works perfectly with GNOME Web and Firefox :ok_hand:

**Comment by seefood** [comment]
Thanks, resolved in Firefox as well.

**Comment by stefanbohacek** [comment]
Great, thank you for confirming!
