### ISSUE TITLE
Enforces left alignment and LTR directionality in RTL blogs

### ISSUE THREAD

**Issue by seefood** [stefanbohacek/detect-missing-adblocker#17]
![image](https://github.com/stefanbohacek/detect-missing-adblocker/assets/409600/a9270766-3f48-4e15-93a6-358f7bab3871)
Hebrew in my case, I have a feeling it will be the same in Arabic, Farsi etc.

I added a span tag, but managed to fix only the directionality, not the alignment. It should really allow the theme's CSS to decide this.
This is my settings editor:
![image](https://github.com/stefanbohacek/detect-missing-adblocker/assets/409600/0ae24a15-95d2-4db3-9e7f-0b4a132d7d02)

however, maybe DO override the look of links. no blue and/or underline makes it impossible to guess if you don't wave over them with a mouse cursor by mistake.

**Comment by seefood** [comment]
found it.
wp-content/plugins/detect-missing-adblocker/dist/css/styles.min.css
.ftf-dma-note is hardcoded aligned to the left. making a PR.

**Comment by stefanbohacek** [comment]
Thank you @seefood! I think a better way to fix this would be using `align-text: start`: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#try_it

Also, updating the styles would require modifying `styles.scss` and compiling the code, so I just went ahead and did that, save you the time getting the project set up locally.

Thank you so much for opening the issue!

**Comment by seefood** [comment]
Sure. I'm a DevOps guy, I last touched HTML work in the 90s :)
