### ISSUE TITLE
Does not detect uBlock Origin on Android

### ISSUE THREAD

**Issue by stefanbohacek** [stefanbohacek/detect-missing-adblocker#19]

**Comment by fullStackRacc** [comment]
Is this still an issue, because it seems to be working for me on Firefox on Android with uBlock Origin installed.

**Comment by iam-py-test** [comment]
It used to be that uBlock Origin disabled generic cosmetic filtering on Android, as (I think) this project relied on detecting generic cosmetic filtering (rules to hide parts of websites which apply to all websites), it didn't work as well on Android. [However, this was recently reversed](https://github.com/gorhill/uBlock/commit/7a768e7b1a7e9248d11101f56075dfa8b654c398).
Thanks

**Comment by stefanbohacek** [comment]
This is great news, thank you both!
